### ISSUE TITLE
0.1 Release Prerequisites

### ISSUE THREAD

**Issue by Michael-F-Bryan** [rust-lang-nursery/mdBook#558]
As @projektir mentioned (https://github.com/rust-lang-nursery/mdBook/issues/482#issuecomment-358526332), it's about time to do a major version bump. Technically this should have been done when the configuration format was updated (#457), but I didn't realise that PR was backwards incompatible until after the fact :disappointed: 

Before we bump from `0.0.x` to `0.1` we'll probably want to resolve the following issues, seeing as they directly affect the user.

- [x] Make sure Appveyor works again so we get compiled binaries (#557) 
- [x] Document as much of the crate as possible (#543)
- [x] Error in console (#559)

(fixes #481, fixes #368)

**Comment by sorin-davidoi** [comment]
I'd say #559 should be fixed as well.

**Comment by Michael-F-Bryan** [comment]
Good idea. I don't know if there are any other issues we *need* to resolve before making a release, but let me know if you can think of anything.

**Comment by sorin-davidoi** [comment]
Including a Rust file seems broken - taking a look (https://rust-lang-nursery.github.io/mdBook/format/rust.html).

**Comment by Michael-F-Bryan** [comment]
Looks like we've checked everything off for this so I'm (finally) going to make another release :tada:

**Comment by Michael-F-Bryan** [comment]
0.1.0 was just published.
